export const SETTING_ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY';
export const SETTING_ANTHROPIC_TOKENIZER_MODEL = 'ANTHROPIC_TOKENIZER_MODEL';
export const WHITELISTED_SETTING_KEYS = [
  SETTING_ANTHROPIC_API_KEY,
  SETTING_ANTHROPIC_TOKENIZER_MODEL,
] as const;
export type WhitelistedSettingKey = (typeof WHITELISTED_SETTING_KEYS)[number];
