export const SETTING_ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY';
export const SETTING_ANTHROPIC_TOKENIZER_MODEL = 'ANTHROPIC_TOKENIZER_MODEL';
export const SETTING_EMBEDDER_URL = 'EMBEDDER_URL';
export const SETTING_EMBEDDER_MODEL = 'EMBEDDER_MODEL';
export const SETTING_EMBEDDER_DIM = 'EMBEDDER_DIM';
export const WHITELISTED_SETTING_KEYS = [
  SETTING_ANTHROPIC_API_KEY,
  SETTING_ANTHROPIC_TOKENIZER_MODEL,
  SETTING_EMBEDDER_URL,
  SETTING_EMBEDDER_MODEL,
  SETTING_EMBEDDER_DIM,
] as const;
export type WhitelistedSettingKey = (typeof WHITELISTED_SETTING_KEYS)[number];
